### ISSUE TITLE
flutter_test version conflict: version solving failed

### ISSUE THREAD

**Issue by CarloRamponi** [apptreesoftware/flutter_map#31]
Hello,
I'm new in flutter and i wanted to use flutter_map to display some maps in my new application.
I started with flutter_map 0.0.1 and there were no problems but once I've updated flutter I had an error (#12) that was solved in version 0.0.3 so I changed the version in my pubspec.yaml from
```
flutter_map: "^0.0.1"
```
to
```
flutter_map: "^0.0.3"
```
But when I try to run
```
flutter packages get
```
I get this error:
```
Running "flutter packages get" in pedibus_app...
Because every version of flutter_test from sdk depends on quiver 0.29.0+1 and flutter_map >=0.0.2
  depends on quiver ^0.28.0, flutter_test from sdk is incompatible with flutter_map >=0.0.2.
So, because pedibus_app depends on both flutter_map ^0.0.3 and flutter_test any from sdk, version
  solving failed.
pub get failed (1)
```
I have found no solutions...

Here is my pubspec.yaml if you need it:
```
name: pedibus_app
description: App for the pedibus project.

dependencies:
  http: "^0.11.3+16"
  flutter_map: "^0.0.3"
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - resources/logo.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages

```

Thanks in advance.
Carlo
